#define MPI_Abort_event 0
#define MPI_Address_event 1
#define MPI_Allgather_event 2
#define MPI_Allgatherv_event 3
#define MPI_Allreduce_event 4
#define MPI_Alltoall_event 5
#define MPI_Alltoallv_event 6
#define MPI_Barrier_event 7
#define MPI_Bcast_event 8
#define MPI_Bsend_event 9
#define MPI_Bsend_init_event 10
#define MPI_Buffer_attach_event 11
#define MPI_Buffer_detach_event 12
#define MPI_Cancel_event 13
#define MPI_Cart_coords_event 14
#define MPI_Cart_create_event 15
#define MPI_Cart_get_event 16
#define MPI_Cart_map_event 17
#define MPI_Cart_rank_event 18
#define MPI_Cart_shift_event 19
#define MPI_Cart_sub_event 20
#define MPI_Cartdim_get_event 21
#define MPI_Comm_compare_event 22
#define MPI_Comm_create_event 23
#define MPI_Comm_dup_event 24
#define MPI_Comm_free_event 25
#define MPI_Comm_get_name_event 26
#define MPI_Comm_group_event 27
#define MPI_Comm_rank_event 28
#define MPI_Comm_remote_group_event 29
#define MPI_Comm_remote_size_event 30
#define MPI_Comm_size_event 31
#define MPI_Comm_split_event 32
#define MPI_Comm_test_inter_event 33
#define MPI_Dims_create_event 34
#define MPI_Errhandler_create_event 35
#define MPI_Errhandler_free_event 36
#define MPI_Errhandler_get_event 37
#define MPI_Error_class_event 38
#define MPI_Error_string_event 39
#define MPI_File_c2f_event 40
#define MPI_File_f2c_event 41
#define MPI_File_set_errhandler_event 42
#define MPI_File_get_errhandler_event 43
#define MPI_File_open_event 44
#define MPI_File_close_event 45
#define MPI_File_delete_event 46
#define MPI_File_set_size_event 47
#define MPI_File_preallocate_event 48
#define MPI_File_get_size_event 49
#define MPI_File_get_group_event 50
#define MPI_File_get_amode_event 51
#define MPI_File_set_info_event 52
#define MPI_File_get_info_event 53
#define MPI_File_set_view_event 54
#define MPI_File_get_view_event 55
#define MPI_File_read_at_event 56
#define MPI_File_read_at_all_event 57
#define MPI_File_write_at_event 58
#define MPI_File_write_at_all_event 59
#define MPI_File_read_event 60
#define MPI_File_read_all_event 61
#define MPI_File_write_event 62
#define MPI_File_write_all_event 63
#define MPI_File_seek_event 64
#define MPI_File_get_position_event 65
#define MPI_File_get_byte_offset_event 66
#define MPI_File_read_shared_event 67
#define MPI_File_write_shared_event 68
#define MPI_File_read_ordered_event 69
#define MPI_File_write_ordered_event 70
#define MPI_File_seek_shared_event 71
#define MPI_File_get_position_shared_event 72
#define MPI_File_read_at_all_begin_event 73
#define MPI_File_read_at_all_end_event 74
#define MPI_File_write_at_all_begin_event 75
#define MPI_File_write_at_all_end_event 76
#define MPI_File_read_all_begin_event 77
#define MPI_File_read_all_end_event 78
#define MPI_File_write_all_begin_event 79
#define MPI_File_write_all_end_event 80
#define MPI_File_read_ordered_begin_event 81
#define MPI_File_read_ordered_end_event 82
#define MPI_File_write_ordered_begin_event 83
#define MPI_File_write_ordered_end_event 84
#define MPI_File_get_type_extent_event 85
#define MPI_File_set_atomicity_event 86
#define MPI_File_get_atomicity_event 87
#define MPI_File_sync_event 88
#define MPI_Finalize_event 89
#define MPI_Finalized_event 90
#define MPI_Gather_event 91
#define MPI_Gatherv_event 92
#define MPI_Get_count_event 93
#define MPI_Get_elements_event 94
#define MPI_Get_processor_name_event 95
#define MPI_Get_version_event 96
#define MPI_Graph_create_event 97
#define MPI_Graph_get_event 98
#define MPI_Graph_map_event 99
#define MPI_Graph_neighbors_count_event 100
#define MPI_Graph_neighbors_event 101
#define MPI_Graphdims_get_event 102
#define MPI_Group_compare_event 103
#define MPI_Group_difference_event 104
#define MPI_Group_excl_event 105
#define MPI_Group_free_event 106
#define MPI_Group_incl_event 107
#define MPI_Group_intersection_event 108
#define MPI_Group_range_excl_event 109
#define MPI_Group_range_incl_event 110
#define MPI_Group_rank_event 111
#define MPI_Group_size_event 112
#define MPI_Group_translate_ranks_event 113
#define MPI_Group_union_event 114
#define MPI_Ibsend_event 115
#define MPI_Info_c2f_event 116
#define MPI_Info_create_event 117
#define MPI_Info_delete_event 118
#define MPI_Info_dup_event 119
#define MPI_Info_f2c_event 120
#define MPI_Info_free_event 121
#define MPI_Info_get_event 122
#define MPI_Info_get_nkeys_event 123
#define MPI_Info_get_nthkey_event 124
#define MPI_Info_get_valuelen_event 125
#define MPI_Info_set_event 126
#define MPI_Init_event 127
#define MPI_Initialized_event 128
#define MPI_Init_thread_event 129
#define MPI_Intercomm_create_event 130
#define MPI_Intercomm_merge_event 131
#define MPI_Iprobe_event 132
#define MPI_Irecv_event 133
#define MPI_Irsend_event 134
#define MPI_Isend_event 135
#define MPI_Issend_event 136
#define MPI_Keyval_create_event 137
#define MPI_Keyval_free_event 138
#define MPI_Op_create_event 139
#define MPI_Op_free_event 140
#define MPI_Pack_event 141
#define MPI_Pack_size_event 142
#define MPI_Pcontrol_event 143
#define MPI_Probe_event 144
#define MPI_Recv_init_event 145
#define MPI_Recv_event 146
#define MPI_Reduce_event 147
#define MPI_Reduce_scatter_event 148
#define MPI_Register_datarep_event 149
#define MPI_Request_free_event 150
#define MPI_Rsend_event 151
#define MPI_Rsend_init_event 152
#define MPI_Scan_event 153
#define MPI_Scatter_event 154
#define MPI_Scatterv_event 155
#define MPI_Send_init_event 156
#define MPI_Send_event 157
#define MPI_Sendrecv_event 158
#define MPI_Sendrecv_replace_event 159
#define MPI_Ssend_init_event 160
#define MPI_Ssend_event 161
#define MPI_Start_event 162
#define MPI_Startall_event 163
#define MPI_Status_set_cancelled_event 164
#define MPI_Status_set_elements_event 165
#define MPI_Testall_event 166
#define MPI_Testany_event 167
#define MPI_Test_event 168
#define MPI_Test_cancelled_event 169
#define MPI_Testsome_event 170
#define MPI_Topo_test_event 171
#define MPI_Waitall_event 172
#define MPI_Waitany_event 173
#define MPI_Wait_event 174
#define MPI_Waitsome_event 175
#define MPI_Wtick_event 176
#define MPI_Wtime_event 177



#define NUM_EVENTS 178

